double pdf_density_rho(double r);
double theta_arms(double r,int choice);
FILE *kick(void *params);
int distrib_init(void *params);
void distrib_init_2(void *params);
int motion(void *params);
void spinvel_angle(void *params);
void gamma_ray_peak_sep(void *params);
int detection(void *params);
void pulse_profile_complete(void *params);
void pulse_profile_complete_2(void *params);
int geometry(void *params);
int radio_flux(void *params);
int gamma_flux(void *params);
//void verif_log_normal(void *params);
double calc_Pdotline(void *params,long np);
double is_dead(double B,double P);
//int is_dead2(void *params,long np);
//int is_dead3(void *params,long np);
int is_dead4(void *params,long np);
int radio_flux_low_freq(void *params);

